language: csharp
os:
  - osx
  - linux

# Ubuntu 16.04
sudo: required
dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta

# OS X 10.12
osx_image: xcode9.2

mono:
  - 5.12.0
  - 5.20.1

#dotnet: 3.0.100-rc1-014190

before_install:
  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin

script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - ./build.sh --target="Travis"

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/gitreleasemanager
    - tools/GitVersion.CommandLine