language: csharp
dist: trusty
osx_image: xcode8.3
mono: 4.2.3
dotnet: 1.0.4
sudo: required
os:
  - osx
  - linux

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 4096; fi

script:
  - ./build.sh

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/gitreleasemanager
    - tools/GitVersion.CommandLine