# Build script
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - develop
    - main
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/
    - adamhathcock-fix_dotnet_restore_settings

# Build cache
cache:
- src\packages -> src\**\packages.config
- tools -> tools\packages.config
